---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gaapi-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - https:
  - http:
      paths:
      - path: /hello(/|$)(.*)
        backend:
          serviceName: hello-world
          servicePort: 80
